# Generated by Django 3.1.2 on 2020-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('delivery_address', models.TextField(max_length=500)),
                ('product_id', models.CharField(max_length=10)),
                ('order_quantity', models.CharField(max_length=7)),
                ('valid', models.CharField(default='True', max_length=10)),
                ('bill_amount', models.IntegerField()),
                ('advance_amount', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.IntegerField()),
                ('Minimum_Order_Quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'app1_product',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Name', models.CharField(max_length=20)),
                ('Product_Id', models.IntegerField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
